import { Division } from "@/lib/type/Struktur/tDivisionDetail";

export const divisions: Division[] = [
  {
    id: "creative-media",
    name: "Creative Media",
    description: "Divisi Creative Media berperan sebagai pusat kreativitas dan pengelolaan informasi visual dalam organisasi. Divisi ini memiliki tanggung jawab untuk mendokumentasikan setiap kegiatan, mengelola konten pada media sosial, serta merancang kebutuhan desain guna mendukung berbagai acara. Dengan memadukan seni, teknologi, dan komunikasi, divisi ini berkomitmen menghasilkan karya yang tidak hanya informatif, tetapi juga menarik dan bermakna, sehingga mampu memperkuat identitas serta citra HIMASI.",
    members: [
      {
        id: "cm-1",
        name: "Azzahra Dara Febrianti",
        image: "/image/Struktur/Deadpool.png",
        role: "Ketua Divisi Creative Media",
        instagram: "https://instagram.com/",
      },
      {
        id: "cm-2",
        name: "Azzahra Dara Febrianti",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "cm-3",
        name: "Azzahra Dara Febrianti",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "cm-4",
        name: "Azzahra Dara Febrianti",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "cm-5",
        name: "Azzahra Dara Febrianti",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
    ],
  },
  {
    id: "public-relation",
    name: "Public Relation",
    description: "Divisi Public Relation merupakan divisi yang berperan aktif dalam menyampaikan, serta menerima informasi kepada civitas dan anggota HIMASI. Divisi ini juga berperan dalam meningkatkan kualitas hubungan eksternal dan internal kampus dan menjadi wadah aspirasi guna terciptanya kegiatan yang efektif dan kolaboratif.",
    members: [
      {
        id: "pr-1",
        name: "Leysa Regita Parhusip",
        image: "/image/Struktur/Deadpool.png",
        role: "Ketua Divisi Public Relation",
        instagram: "https://instagram.com/",
      },
      {
        id: "pr-2",
        name: "Leysa Regita Parhusip",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "pr-3",
        name: "Leysa Regita Parhusip",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "pr-4",
        name: "Leysa Regita Parhusip",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "pr-5",
        name: "Leysa Regita Parhusip",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
    ],
  },
  {
    id: "research-and-development",
    name: "Research and Development",
    description: "Divisi Research and Development (R&D) bertugas sebagai pendorong inovasi dan solusi teknologi HIMASI. Dengan bergerak melampui sekadar eksplorasi, divisi ini mempraktikkan pendekatan strategis dan berbasis data untuk mentransformasi ide-ide baru menjadi produk dan layanan digital yang memiliki dampak nyata.",
    members: [
      {
        id: "rd-1",
        name: "Raden Whisnu Arya Nugraha",
        image: "/image/Struktur/Deadpool.png",
        role: "Ketua Divisi Research and Development",
        instagram: "https://instagram.com/",
      },
      {
        id: "rd-2",
        name: "Raden Whisnu Arya Nugraha",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "rd-3",
        name: "Raden Whisnu Arya Nugraha",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "rd-4",
        name: "Raden Whisnu Arya Nugraha",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "rd-5",
        name: "Raden Whisnu Arya Nugraha",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
    ],
  },
  {
    id: "human-talent-development",
    name: "Human Talent Development",
    description: "Divisi Human Talent Development (HTD) merupakan wadah bagi mahasiswa Sistem Informasi untuk mengembangkan potensi, baik pada bidang akademik maupun non-akademik. Divisi ini berperan dalam menggali minat serta bakat, kemudian memfasilitasinya melalui program inovatif dan berkesinambungan. Dengan menjunjung sportivitas, solidaritas, kreativitas, dan keunggulan, HTD menciptakan lingkungan yang mendukung mahasiswa berkembang secara optimal, sekaligus, membentuk generasi berdaya saing tinggi yang mampu memberikan kontribusi nyata.",
    members: [
      {
        id: "htd-1",
        name: "Andhika Pratama",
        image: "/image/Struktur/Deadpool.png",
        role: "Ketua Divisi Human Talent Development",
        instagram: "https://instagram.com/",
      },
      {
        id: "htd-2",
        name: "Andhika Pratama",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "htd-3",
        name: "Andhika Pratama",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "htd-4",
        name: "Andhika Pratama",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "htd-5",
        name: "Andhika Pratama",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
    ],
  },
  {
    id: "entrepreneurship",
    name: "Entrepreneurship",
    description: "Divisi Entrepreneurship merupakan wadah bagi mahasiswa untuk mengembangkan jiwa serta keterampilan berwirausaha dengan misi merealisasikan gagasan inovatif menjadi usaha yang produktif. melalui berbagai program, seperti pembuatan merchandise, penyelenggaraan bazar, dan inisiatif bisnis lainnya, divisi ini tidak hanya berfokus pada keuntungan, tetapi juga pada pengembangan diri anggota. Di dalamnya, mahasiswa berkesempatan belajar secara langsung mengenai manajemen keuangan, strategi pemasaran, hingga pelaksanaan proyek, sehingga dapat membentuk pengalaman berharga dalam menghadapi dunia nyata.",
    members: [
      {
        id: "ent-1",
        name: "Laili Salsabila",
        image: "/image/Struktur/Deadpool.png",
        role: "Ketua Divisi Entrepreneurship",
        instagram: "https://instagram.com/",
      },
      {
        id: "ent-2",
        name: "Laili Salsabila",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "ent-3",
        name: "Laili Salsabila",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "ent-4",
        name: "Laili Salsabila",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
      {
        id: "ent-5",
        name: "Laili Salsabila",
        image: "/image/Struktur/Deadpool.png",
        role: "Anggota",
        instagram: "https://instagram.com/",
      },
    ],
  },
]
